#!/usr/bin/env bash
# index.sh — per-bucket cached index of changes for fast picker startup.
#
# Each bucket has a canonical YAML index at
#   .foundry/changes/<bucket>/.index.yaml
# that denormalizes the four fields the main picker renders (title +
# created_at + updated_at + their cached epoch equivalents) so reading
# N rows costs one awk fork per bucket instead of N×3 grep|sed forks.
#
# Per-slug tracking.yaml remains the source of truth — the index is
# rebuilt from those files by `foundry sync` (or lazily on first launch
# when an index file is missing) and incrementally maintained by
# cmd_new / cmd_move / tracking.sh set.
#
# Format — canonical YAML, one block per entry:
#   # .foundry/changes/<bucket>/.index.yaml
#   # auto-generated by foundry — do not edit by hand; run `foundry sync` to rebuild
#   version: 1
#   bucket: <bucket>
#   generated_at: <ISO-8601 UTC>
#   entries:
#     - slug: <kebab>
#       title: <free text, single-line>
#       created_at: <ISO-8601 UTC>
#       updated_at: <ISO-8601 UTC>
#       created_epoch: <unix seconds>
#       updated_epoch: <unix seconds>
#
# Source this file; do not execute it. Functions are namespaced index_*.

_INDEX_FILENAME=".index.yaml"
_INDEX_VERSION=1

# Pull in BUCKETS if the caller hasn't already sourced constants.sh.
if [[ -z "${BUCKETS:-}" ]]; then
  _INDEX_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  # shellcheck source=../config/constants.sh
  . "$_INDEX_SCRIPT_DIR/../config/constants.sh"
fi

_index_changes_dir() { echo "${FOUNDRY_ROOT:-$PWD/.foundry}/changes"; }
_index_path()        { echo "$(_index_changes_dir)/$1/$_INDEX_FILENAME"; }
_index_now()         { date -u +"%Y-%m-%dT%H:%M:%SZ"; }

# Convert ISO-8601 UTC to unix epoch seconds; echoes 0 on failure.
_index_iso_to_epoch() {
  local iso="$1"
  [[ -z "$iso" ]] && { echo 0; return; }
  date -j -u -f "%Y-%m-%dT%H:%M:%SZ" "$iso" +%s 2>/dev/null \
    || date -u -d "$iso" +%s 2>/dev/null \
    || echo 0
}

# If $1 is .foundry/changes/<bucket>/<slug>, echo "<bucket>\t<slug>";
# else exit nonzero. Used by tracking.sh set to find the right index.
index_locate_dir() {
  local dir="${1%/}"
  local slug; slug=$(basename "$dir")
  local bucket_dir; bucket_dir=$(dirname "$dir")
  local bucket; bucket=$(basename "$bucket_dir")
  local changes_dir; changes_dir=$(dirname "$bucket_dir")
  [[ "$(basename "$changes_dir")" == "changes" ]] || return 1
  local b
  for b in "${BUCKETS[@]}"; do
    if [[ "$b" == "$bucket" ]]; then
      printf '%s\t%s\n' "$bucket" "$slug"
      return 0
    fi
  done
  return 1
}

# Emit TSV "slug\ttitle\tcreated_at\tupdated_at\tcreated_epoch\tupdated_epoch"
# — one line per entry. Single awk pass over the index file.
# Returns nonzero (and emits nothing) if the index doesn't exist, so the
# caller can fall back to a rebuild + retry.
index_read_bucket() {
  local f; f=$(_index_path "$1")
  [[ -f "$f" ]] || return 1
  awk '
    function emit() {
      if (slug != "") {
        printf("%s\t%s\t%s\t%s\t%s\t%s\n", slug, title, ct, ut, ce, ue)
      }
      slug=""; title=""; ct=""; ut=""; ce="0"; ue="0"
    }
    /^  - slug:/        { emit(); sub(/^  - slug:[[:space:]]*/, "");        slug=$0;  next }
    /^    title:/       { sub(/^    title:[[:space:]]*/, "");               title=$0; next }
    /^    created_at:/  { sub(/^    created_at:[[:space:]]*/, "");          ct=$0;    next }
    /^    updated_at:/  { sub(/^    updated_at:[[:space:]]*/, "");          ut=$0;    next }
    /^    created_epoch:/ { sub(/^    created_epoch:[[:space:]]*/, "");     ce=$0;    next }
    /^    updated_epoch:/ { sub(/^    updated_epoch:[[:space:]]*/, "");     ue=$0;    next }
    END { emit() }
  ' "$f"
}

# Helpers used by both rebuild and incremental write paths.
_index_read_field() {
  # $1=file, $2=field. Mirrors yaml_get in tracking.sh but inlined to
  # avoid a tracking.sh fork per field.
  grep -E "^$2:( |\$)" "$1" 2>/dev/null | head -n1 | sed -E "s/^$2:[[:space:]]?//"
}

_index_write_entry_block() {
  # Append one entry block to stdout. Args: slug title ct ut ce ue.
  printf '  - slug: %s\n'          "$1"
  printf '    title: %s\n'         "$2"
  printf '    created_at: %s\n'    "$3"
  printf '    updated_at: %s\n'    "$4"
  printf '    created_epoch: %s\n' "$5"
  printf '    updated_epoch: %s\n' "$6"
}

_index_write_header() {
  # $1=bucket. Writes index preamble (everything before entry blocks).
  printf '# .foundry/changes/%s/%s\n' "$1" "$_INDEX_FILENAME"
  printf '# auto-generated by foundry — do not edit by hand; run `foundry sync` to rebuild\n'
  printf 'version: %s\n'      "$_INDEX_VERSION"
  printf 'bucket: %s\n'       "$1"
  printf 'generated_at: %s\n' "$(_index_now)"
  printf 'entries:\n'
}

# Full rebuild of one bucket. Scans every slug folder, reads its
# tracking.yaml, writes a fresh .index.yaml atomically.
index_rebuild_bucket() {
  local bucket="$1"
  local dir; dir="$(_index_changes_dir)/$bucket"
  [[ -d "$dir" ]] || return 0
  local f; f=$(_index_path "$bucket")
  local tmp; tmp=$(mktemp)
  _index_write_header "$bucket" > "$tmp"
  shopt -s nullglob
  local entry slug tracking title ct ut ce ue
  for entry in "$dir"/*/; do
    slug=$(basename "$entry")
    tracking="$entry/tracking.yaml"
    [[ -f "$tracking" ]] || continue
    title=$(_index_read_field   "$tracking" title)
    ct=$(_index_read_field      "$tracking" created_at)
    ut=$(_index_read_field      "$tracking" updated_at)
    ce=$(_index_iso_to_epoch    "$ct")
    ue=$(_index_iso_to_epoch    "$ut")
    _index_write_entry_block "$slug" "$title" "$ct" "$ut" "$ce" "$ue" >> "$tmp"
  done
  shopt -u nullglob
  mv "$tmp" "$f"
}

# Rebuild every bucket's index. Used by `foundry sync` and as the lazy
# fallback when an expected index is missing.
index_rebuild_all() {
  local b
  for b in "${BUCKETS[@]}"; do
    index_rebuild_bucket "$b"
  done
}

# Append one entry block to a bucket's index. Used by cmd_new and the
# destination side of cmd_move. If the index is missing, rebuild it
# from scratch — the new slug will be picked up by the scan.
index_add_entry() {
  local bucket="$1" slug="$2" title="$3" ct="$4" ut="$5"
  local f; f=$(_index_path "$bucket")
  if [[ ! -f "$f" ]]; then
    index_rebuild_bucket "$bucket"
    return
  fi
  local ce ue
  ce=$(_index_iso_to_epoch "$ct")
  ue=$(_index_iso_to_epoch "$ut")
  _index_write_entry_block "$slug" "$title" "$ct" "$ut" "$ce" "$ue" >> "$f"
}

# Remove a slug's entry block from a bucket's index. Used by the source
# side of cmd_move. Missing index ⇒ nothing to do.
index_remove_entry() {
  local bucket="$1" slug="$2"
  local f; f=$(_index_path "$bucket")
  [[ -f "$f" ]] || return 0
  local tmp; tmp=$(mktemp)
  awk -v target="$slug" '
    function flush() {
      if (block != "" && key != target) printf("%s", block)
      block=""; key=""
    }
    /^  - slug:/ {
      flush()
      key = $0; sub(/^  - slug:[[:space:]]*/, "", key)
      block = $0 "\n"
      next
    }
    /^    / && block != "" { block = block $0 "\n"; next }
    { flush(); print }
    END { flush() }
  ' "$f" > "$tmp"
  mv "$tmp" "$f"
}

# Update one or more fields of an existing slug's entry block.
# Args after slug come in (field, value) pairs. Unknown fields are
# silently ignored; missing entry ⇒ no-op. If updated_at or
# created_at is among the updates, the corresponding *_epoch is
# refreshed automatically (the caller doesn't have to compute it).
index_update_entry() {
  local bucket="$1" slug="$2"; shift 2
  local f; f=$(_index_path "$bucket")
  [[ -f "$f" ]] || return 0
  # Build a parallel pairs file: "field<TAB>value" per line.  Pass it
  # to awk via -v ENV-style isn't enough for multi-value, so we use a
  # here-doc on stdin and merge with the index file via getline.
  local pairs; pairs=$(mktemp)
  while [[ $# -ge 2 ]]; do
    printf '%s\t%s\n' "$1" "$2" >> "$pairs"
    # Auto-derive *_epoch when a timestamp field changes.
    case "$1" in
      created_at) printf 'created_epoch\t%s\n' "$(_index_iso_to_epoch "$2")" >> "$pairs" ;;
      updated_at) printf 'updated_epoch\t%s\n' "$(_index_iso_to_epoch "$2")" >> "$pairs" ;;
    esac
    shift 2
  done
  local tmp; tmp=$(mktemp)
  awk -v target="$slug" -v pairs="$pairs" '
    BEGIN {
      while ((getline line < pairs) > 0) {
        i = index(line, "\t")
        if (i > 0) val[substr(line, 1, i - 1)] = substr(line, i + 1)
      }
      close(pairs)
    }
    /^  - slug:/ {
      m = $0; sub(/^  - slug:[[:space:]]*/, "", m)
      in_entry = (m == target)
      print; next
    }
    in_entry && /^    [a-z_]+:/ {
      f = $0
      sub(/^    /, "", f)
      i = index(f, ":")
      if (i > 0) {
        key = substr(f, 1, i - 1)
        if (key in val) {
          printf("    %s: %s\n", key, val[key]); next
        }
      }
      print; next
    }
    /^[^ ]/ { in_entry = 0; print; next }
    { print }
  ' "$f" > "$tmp"
  mv "$tmp" "$f"
  rm -f "$pairs"
}

# Convenience: called by tracking.sh set after a per-slug field write.
# Extracts (bucket, slug) from the slug folder path and updates the
# matching index entry. Silently no-ops when $1 is not a slug folder
# under .foundry/changes/ (e.g. tracking.sh invoked on a stray path).
index_touch_entry() {
  local dir="$1" field="$2" value="$3"
  local located bucket slug
  located=$(index_locate_dir "$dir") || return 0
  IFS=$'\t' read -r bucket slug <<< "$located"
  index_update_entry "$bucket" "$slug" "$field" "$value"
}
